# Use the Catppuccin Mocha palette names in styles below
palette = "catppuccin_mocha"

# ── Global layout ─────────────────────────────────────────────
# Line 1: user@host + directory + selected dev modules
# Line 2: date/time + kubernetes
# Then the prompt character on a new line.
format = """
$username$hostname$directory $git_branch$git_status$nodejs$python$ruby
$time$kubernetes
$character
"""

# ── Prompt symbols ────────────────────────────────────────────
[character]
success_symbol = '[❯❯❯❯](teal bold)'
error_symbol   = '[XXXX](red bold)'
vicmd_symbol   = '[❮❮❮❮](mauve bold)'

# ── Common modules ────────────────────────────────────────────
[username]
show_always = true
style_user  = 'mauve bold'       # you on mocha
style_root  = 'text bold'        # root stands out
format      = '[$user]($style)@'

[hostname]
ssh_only = false
format   = '[$hostname](teal bold) '

[directory]
style               = 'blue bold'
truncation_length   = 0
truncate_to_repo    = false

[time]
disabled     = false
style        = 'mauve bold'
format       = '[\[$time\]]($style) '
time_format  = '%Y-%m-%d %H:%M'   # change to taste

[kubernetes]
disabled = false
# Cluster in green, namespace in teal for quick scanning
format   = '[$cluster](green bold) [$namespace](teal bold) '

[battery]
disabled = true

[gcloud]
disabled = true

[ruby]
detect_variables = []
detect_files     = ['Gemfile', '.ruby-version']

# ── Catppuccin Mocha palette ─────────────────────────────────
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo  = "#f2cdcd"
pink      = "#f5c2e7"
mauve     = "#cba6f7"
red       = "#f38ba8"
maroon    = "#eba0ac"
peach     = "#fab387"
yellow    = "#f9e2af"
green     = "#a6e3a1"
teal      = "#94e2d5"
sky       = "#89dceb"
sapphire  = "#74c7ec"
blue      = "#89b4fa"
lavender  = "#b4befe"
text      = "#cdd6f4"
subtext1  = "#bac2de"
subtext0  = "#a6adc8"
overlay2  = "#9399b2"
overlay1  = "#7f849c"
overlay0  = "#6c7086"
surface2  = "#585b70"
surface1  = "#45475a"
surface0  = "#313244"
base      = "#1e1e2e"
mantle    = "#181825"
crust     = "#11111b"
